# Generated by Django 4.1.3 on 2022-11-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_profile_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow',
        ),
    ]
