# Generated by Django 4.1.3 on 2022-11-15 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
